meta_product_name: "Roger That!"
meta_title: "Roger That! - Le tennis est à vous"
meta_description: "Relevant description"
meta_image: "app/assets/filet.jpg/"
twitter_account: "@product_twitter_account"   # required for Twitter Cards
